force-app/main/default/objects/ReportSender__c/ReportSender__c.object-meta.xml
<CustomObject>
    <label>Report Sender</label>
    <nameField>
        <label>Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reports Sender</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReportSender__c/fields/Cron__c.field-meta.xml
<CustomField>
    <fullName>Cron__c</fullName>
    <label>Cron</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportSender__c/fields/IsCron__c.field-meta.xml
<CustomField>
    <fullName>IsCron__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCron</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ReportSenderSchController.cls
public class ReportSenderSchController {

    @AuraEnabled
    public static void setSchedulable(Id recordId) {

        List<ReportSender__c> reportSender = [
            SELECT Id, Name, Cron__c, IsCron__c, Report_Name__c
            FROM ReportSender__c
            WHERE Id = :recordId
        ];

        if (reportSender.isEmpty()) {
            throw new AuraHandledException(Label.errMsgReportIsNotFound);
        } else {
            String cronValue = reportSender[0].Cron__c;
            String reportSenderName = reportSender[0].Name;
            Boolean isCron = reportSender[0].IsCron__c;

            if (isCron) {
                throw new AuraHandledException(Label.SchedulableAlreadyExists);
            }

            try {
                System.schedule(reportSenderName, cronValue, new ReportSenderSch(recordId));
                ReportSenderSchController.setSchedulableStatus(reportSender);
            } catch (Exception e){
                throw new AuraHandledException(e.getMessage());
            }
        }
    }

    private static void setSchedulableStatus(List<ReportSender__c> reportSenderList) {

        for (ReportSender__c reportSender : reportSenderList) {
            reportSender.IsCron__c = true;
        }

        update reportSenderList;
    }
}