force-app/main/default/objects/ReportSender__c/ReportSender__c.object-meta.xml
<CustomObject>
    <label>Report Sender</label>
    <nameField>
        <label>Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reports Sender</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReportSender__c/fields/Cron__c.field-meta.xml
<CustomField>
    <fullName>Cron__c</fullName>
    <label>Cron</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportSender__c/fields/IsCron__c.field-meta.xml
<CustomField>
    <fullName>IsCron__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCron</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ReportSenderSchRemoverController.cls
public class ReportSenderSchRemoverController {

    @AuraEnabled
    public static void removeSchedulable(Id recordId) {

        List<ReportSender__c> reportSender = [
            SELECT Id, Name, Cron__c, IsCron__c
            FROM ReportSender__c
            WHERE Id = :recordId
        ];

        if (reportSender.isEmpty()) {
            throw new AuraHandledException(Label.errMsgReportIsNotFound);
        } else {
            Boolean isCron = reportSender[0].IsCron__c;

            if (!isCron) {
                throw new AuraHandledException(Label.SchedulableDoesNotExist);
            }

            List<CronTrigger> jobList = [
                SELECT Id, CronJobDetail.Name
                FROM CronTrigger
                WHERE CronJobDetail.Name = :reportSender[0].Name
            ];

            for (CronTrigger job : jobList) {
                System.abortJob(job.id);
            }

            ReportSenderSchRemoverController.setCronStatus(reportSender);
        }
    }

    private static void setCronStatus(List<ReportSender__c> reportSenderList) {

        for (ReportSender__c reportSender : reportSenderList) {
            reportSender.IsCron__c = false;
        }

        update reportSenderList;
    }
}